---
- name: 2
  hosts: m1
  remote_user: devops
  gather_facts: no
  tasks:
  - name: first task
    command: hostname
    notify:
      - test1
      - test2

  - name: second task
    debug:
      msg: last module

  handlers:
  - name: test1
    debug:
      msg: this is test1

  - name: test2
    debug:
      msg: this is test2
