---
- name: 3
  hosts: m1
  remote_user: devops
  gather_facts: no
  tasks:
  - name: first task
    command: hostname
    notify:
      - test1
      
  - name: second task
    debug:
      msg: last module

  handlers:
  - name: test1
    debug:
      msg: this is test1

  - name: test1
    debug:
      msg: this is test1-1
